import postgres from "postgres";

const DATABASE_URL =
  "postgres://postgres:BHmmeE8gAR5ngRaYPjyyl9H3xGKYScUgC9RjiLxFZSvsfUmt4MsIHdpgGoMwvTDJ@194.87.161.199:5431/postgres";

const sql = postgres(DATABASE_URL, { max: 1 });

const rest1Id = "rest-kebab";
const rest2Id = "rest-pyramids";

async function seed() {
  console.log("🌱 Seeding menu categories...");

  const categories = [
    ["cat-grills",         rest1Id, "Grills & Kebab",             "مشويات وكباب",             1],
    ["cat-starters",       rest1Id, "Starters & Mezza",           "المقبلات والميزة",          2],
    ["cat-salads",         rest1Id, "Fresh Salads",               "سلطات طازجة",               3],
    ["cat-soups",          rest1Id, "Soups",                      "شوربات",                    4],
    ["cat-drinks",         rest1Id, "Cold & Hot Drinks",          "مشروبات باردة وساخنة",      5],
    ["cat-desserts",       rest1Id, "Desserts",                   "حلويات",                    6],
    ["cat-pyra-coffee",    rest2Id, "Coffee & Teas",              "قهوة وشاي",                 1],
    ["cat-pyra-breakfast", rest2Id, "Egyptian Breakfast",         "إفطار مصري",                2],
    ["cat-pyra-juices",    rest2Id, "Fresh Juices & Smoothies",   "عصائر طازجة وسموذي",        3],
    ["cat-pyra-pastries",  rest2Id, "Pastries & Sweets",          "مخبوزات وحلويات",           4],
  ];

  for (const [id, biz, name, name_ar, sort_order] of categories) {
    await sql`
      INSERT INTO menu_categories (id, business_id, name, name_ar, sort_order)
      VALUES (${id}, ${biz}, ${name}, ${name_ar}, ${sort_order})
      ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, name_ar=EXCLUDED.name_ar, sort_order=EXCLUDED.sort_order
    `;
  }
  console.log("✅ " + categories.length + " categories upserted");

  console.log("🌱 Seeding menu items...");

  const items = [
    ["item-kebab-mix", rest1Id, "cat-grills",
      "Mix Grill Platter (500g)", "مشويات مشكلة 500 جرام",
      "A lavish sharing platter of juicy lamb kofta, marinated shish tawook, and authentic charcoal-grilled kebab, served with saffron rice, warm baladi bread, grilled tomatoes & tahina dip.",
      "طبق مشويات مشترك فاخر يضم كفتة ضأن عصيرية وشيش طاووق متبل وكباب مشوي على الفحم الأصيل، يُقدَّم مع أرز بالزعفران وخبز بلدي دافئ وطماطم مشوية وطحينة.",
      450.0, "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":860,"tags":["halal","grilled","lamb","chicken","sharing","popular"]}'],
    ["item-kofta", rest1Id, "cat-grills",
      "Egyptian Lamb Kofta (6 pcs)", "كفتة ضأن مصرية 6 قطع",
      "Hand-shaped minced lamb kofta seasoned with cumin, coriander, parsley and a secret blend of oriental spices, char-grilled to perfection. Served with pita bread and tahina.",
      "كفتة ضأن مفرومة يدوياً متبلة بالكمون والكزبرة والبقدونس وخليط من البهارات الشرقية السرية، مشوية على الفحم بإتقان، تُقدَّم مع خبز بيتا وطحينة.",
      280.0, "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":520,"tags":["halal","grilled","lamb","spicy","popular"]}'],
    ["item-shish", rest1Id, "cat-grills",
      "Shish Tawook Skewers (4 pcs)", "شيش طاووق 4 أسياخ",
      "Tender chicken breast cubes marinated overnight in garlic, lemon juice, yogurt and aromatic spices, then grilled over glowing charcoal until golden. Served with garlic sauce and fries.",
      "قطع صدر دجاج طرية متبلة طوال الليل في الثوم وعصير الليمون والزبادي والبهارات العطرية، مشوية على الفحم المتقد حتى تصبح ذهبية. تُقدَّم مع صلصة ثوم وبطاطس.",
      240.0, "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":420,"tags":["halal","grilled","chicken","marinated","light"]}'],
    ["item-lamb-chops", rest1Id, "cat-grills",
      "Grilled Lamb Chops (4 pcs)", "ضلوع خروف مشوية 4 قطع",
      "Premium New Zealand lamb chops rubbed with rosemary, garlic and Egyptian spice blend, charcoal-grilled to a beautiful pink medium. Served with roasted vegetables and mint yogurt sauce.",
      "ضلوع خروف نيوزيلندي ممتازة مدهونة بالروزماري والثوم وخليط البهارات المصرية، مشوية على الفحم لدرجة متوسطة ورديّة جميلة. تُقدَّم مع خضار مشوية وصلصة زبادي بالنعناع.",
      380.0, "https://images.unsplash.com/photo-1544365558-35aa4afcf11f?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":680,"tags":["halal","grilled","lamb","premium","gluten-free"]}'],
    ["item-whole-chicken", rest1Id, "cat-grills",
      "Charcoal Whole Chicken", "دجاجة كاملة على الفحم",
      "A whole free-range chicken marinated for 24 hours in lemon, garlic, cumin and Egyptian herbs, slow-grilled over charcoal until deeply smoky and fall-off-the-bone tender.",
      "دجاجة كاملة من الدواجن الحرة متبلة لمدة 24 ساعة في الليمون والثوم والكمون والأعشاب المصرية، مشوية ببطء على الفحم حتى تصبح مدخنة وطرية جداً.",
      320.0, "https://images.unsplash.com/photo-1598103442097-8b74394b95c1?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":1150,"tags":["halal","grilled","chicken","sharing","classic"]}'],
    ["item-beef-liver", rest1Id, "cat-grills",
      "Spiced Grilled Beef Liver", "كبدة بتلو مشوية بالبهارات",
      "Thinly sliced fresh beef liver flash-grilled with chili, cumin, garlic and green peppers in the authentic Alexandrian style. Served with tomato, onion and baladi bread.",
      "شرائح كبدة بتلو طازجة مشوية سريعاً مع الفلفل الحار والكمون والثوم والفلفل الأخضر على الطريقة الإسكندرانية الأصيلة. تُقدَّم مع طماطم وبصل وخبز بلدي.",
      180.0, "https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":340,"tags":["halal","grilled","offal","spicy","alexandrian"]}'],
    ["item-tahina", rest1Id, "cat-starters",
      "Creamy Sesame Tahina", "طحينة سمسم ناعمة",
      "House-made pure sesame tahina blended with roasted garlic, fresh lemon juice, cumin, and extra-virgin olive oil. Sprinkled with paprika and parsley. Served with warm baladi bread.",
      "طحينة سمسم نقية من صنع المطبخ ممزوجة بالثوم المحمص وعصير الليمون الطازج والكمون وزيت الزيتون البكر. مرشوشة بالفليفلة الحمراء والبقدونس. تُقدَّم مع خبز بلدي دافئ.",
      40.0, "https://images.unsplash.com/photo-1541544741938-0af808871cc0?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":185,"tags":["vegetarian","vegan","gluten-free","sesame","dip"]}'],
    ["item-baba", rest1Id, "cat-starters",
      "Smoked Baba Ghanoush", "بابا غنوج مشوي",
      "Whole eggplants charred over an open flame until deeply smoky, then hand-mashed with tahina, roasted garlic, lemon juice and olive oil. Finished with pomegranate seeds and fresh mint.",
      "باذنجان كامل محروق على لهب مفتوح حتى يصبح مدخناً عميقاً، ثم يُهرس يدوياً مع الطحينة والثوم المشوي وعصير الليمون وزيت الزيتون. يُزين ببذور الرمان والنعناع الطازج.",
      50.0, "https://images.unsplash.com/photo-1572449043416-55f4685c9bb7?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":150,"tags":["vegetarian","vegan","gluten-free","smoky","eggplant"]}'],
    ["item-hummus", rest1Id, "cat-starters",
      "Silky Lebanese Hummus", "حمص لبناني ناعم",
      "Slow-cooked chickpeas blended into a silky-smooth hummus with generous tahina, lemon juice, garlic and ice water, topped with warm chickpeas and a river of olive oil.",
      "حمص مطبوخ ببطء ومُمزوج في حمص ناعم كالحرير مع طحينة سخية وعصير ليمون وثوم وماء مثلج، مُزيَّن بحمص دافئ ونهر من زيت الزيتون.",
      55.0, "https://images.unsplash.com/photo-1612177726700-bd1739cdb77b?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":210,"tags":["vegetarian","vegan","gluten-free","chickpeas","protein"]}'],
    ["item-vine-leaves", rest1Id, "cat-starters",
      "Stuffed Vine Leaves (8 pcs)", "ورق عنب محشي 8 قطع",
      "Tender vine leaves hand-rolled with Egyptian short-grain rice, diced tomatoes, parsley, mint, lemon zest and olive oil. Served chilled with a wedge of lemon.",
      "ورق عنب طري مدلفن يدوياً بالأرز المصري قصير الحبة والطماطم المفرومة والبقدونس والنعناع وقشر الليمون وزيت الزيتون. يُقدَّم بارداً مع شريحة ليمون.",
      70.0, "https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":280,"tags":["vegetarian","vegan","rice","herbed","cold"]}'],
    ["item-mixed-mezza", rest1Id, "cat-starters",
      "Grand Mixed Mezza Platter", "طبق ميزة مشكل كبير",
      "A feast for sharing — tahina, baba ghanoush, hummus, vine leaves, olives, feta cheese, pickled turnip and radish, served with warm baladi bread. Perfect for 3-4 people.",
      "وليمة للمشاركة — طحينة وبابا غنوج وحمص وورق عنب وزيتون وجبن فيتا ولفت مخلل وفجل، تُقدَّم مع سلة من الخبز البلدي الدافئ. مثالية لـ 3-4 أشخاص.",
      120.0, "https://images.unsplash.com/photo-1515516008080-2c55302901b7?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":480,"tags":["vegetarian","sharing","assorted","popular"]}'],
    ["item-fattoush", rest1Id, "cat-salads",
      "Classic Fattoush Salad", "سلطة فتوش كلاسيكية",
      "Crispy romaine, cucumber, tomato, radish, spring onion and fresh mint tossed with sumac-lemon dressing and golden crispy pita chips.",
      "خس روماني مقرمش وخيار وطماطم وفجل وبصل أخضر ونعناع طازج بتتبيلة السماق والليمون مع رقائق بيتا مقرمشة ذهبية.",
      65.0, "https://images.unsplash.com/photo-1540189549336-e6e99eb4b51b?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":130,"tags":["vegetarian","vegan","sumac","crispy","light"]}'],
    ["item-tabboule", rest1Id, "cat-salads",
      "Lebanese Tabbouleh", "تبولة لبنانية",
      "Authentic herb-forward salad with finely chopped flat-leaf parsley, fresh mint, ripe tomatoes and fine bulgur wheat, dressed in extra-virgin olive oil and lemon juice.",
      "سلطة أعشاب أصيلة ببقدونس ناعم مفروم ونعناع طازج وطماطم ناضجة وبرغل ناعم، متبلة بزيت الزيتون البكر وعصير الليمون.",
      60.0, "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":120,"tags":["vegetarian","vegan","herbs","parsley","light"]}'],
    ["item-caesar", rest1Id, "cat-salads",
      "Grilled Chicken Caesar", "سيزر بالدجاج المشوي",
      "Crisp romaine hearts tossed in house-made Caesar dressing with shaved Parmesan, house-baked croutons and sliced grilled chicken breast.",
      "قلوب خس روماني مقرمشة بصلصة سيزر منزلية مع شرائح بارميزان ومقرمشات مخبوزة يدوياً وشرائح صدر دجاج مشوي.",
      90.0, "https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":320,"tags":["chicken","crispy","creamy","parmesan"]}'],
    ["item-lentil-soup", rest1Id, "cat-soups",
      "Egyptian Red Lentil Soup", "شوربة عدس مصرية",
      "Velvety golden soup of slow-simmered red lentils with caramelized onions, cumin, coriander and turmeric, finished with lemon juice and crispy onion rings. Served with bread.",
      "شوربة مخملية ذهبية من العدس الأحمر مع البصل المكرمل والكمون والكزبرة والكركم، مُنهاة بعصير ليمون وحلقات بصل مقلية مقرمشة. تُقدَّم مع الخبز.",
      55.0, "https://images.unsplash.com/photo-1547592180-85f173990554?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":210,"tags":["vegetarian","vegan","gluten-free","lentils","warm"]}'],
    ["item-tomato-soup", rest1Id, "cat-soups",
      "Roasted Tomato & Basil Soup", "شوربة طماطم مشوية بالريحان",
      "Slow-roasted vine tomatoes blended with caramelized garlic, fresh basil and a touch of cream into a velvety soup. Finished with basil oil and toasted bread.",
      "طماطم كرمة مشوية ببطء ممزوجة بالثوم المكرمل والريحان الطازج ولمسة كريمة في شوربة مخملية. مُنهاة بزيت ريحان وخبز محمص.",
      50.0, "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":180,"tags":["vegetarian","tomato","basil","creamy","warm"]}'],
    ["item-mint-lemon", rest1Id, "cat-drinks",
      "Fresh Mint Lemonade", "ليمون بالنعناع طازج",
      "Freshly squeezed Egyptian lemons muddled with garden-fresh mint leaves, a touch of sugar and crushed ice — the perfect antidote to a hot Cairo day.",
      "ليمون مصري مضغوط طازجاً مع أوراق نعناع طازجة ولمسة سكر وثلج مجروش — الترياق المثالي ليوم قاهري حار.",
      45.0, "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":95,"tags":["cold","fresh","mint","lemon","vegan"]}'],
    ["item-hibiscus", rest1Id, "cat-drinks",
      "Iced Karkadeh (Hibiscus)", "كركديه مثلج",
      "Premium dried hibiscus flowers steeped overnight in cold-filtered water with rose water and sugar, served over crushed ice. Naturally rich in antioxidants and Vitamin C.",
      "أزهار كركديه مجففة ممتازة منقوعة طوال الليل في ماء مفلتر بارد مع ماء ورد وقليل من السكر، تُقدَّم على ثلج مجروش.",
      35.0, "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":60,"tags":["cold","antioxidant","herbal","vegan","vitamin-c"]}'],
    ["item-mango-juice", rest1Id, "cat-drinks",
      "Fresh Egyptian Mango Juice", "عصير مانجو مصري طازج",
      "Egyptian Alphonso mangoes blended fresh with milk and honey into an impossibly thick, golden juice. Seasonal summer special.",
      "مانجو الفونسو المصرية مُمزوجة طازجة مع الحليب والعسل في عصير ذهبي كثيف. خاص موسمي صيفي.",
      60.0, "https://images.unsplash.com/photo-1527661591475-527312dd65f5?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":190,"tags":["cold","fresh","mango","seasonal","tropical"]}'],
    ["item-ayran", rest1Id, "cat-drinks",
      "Chilled Ayran Yogurt Drink", "عيران زبادي بارد",
      "A refreshingly tangy Turkish-style yogurt drink whisked with cold water and a pinch of salt until perfectly frothy. The best companion for grilled meats.",
      "مشروب زبادي منعش على الطريقة التركية مخفوقاً مع ماء بارد وقرصة ملح حتى يصبح رغوياً تماماً. أفضل مشروب مع المشويات.",
      30.0, "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":110,"tags":["cold","probiotic","yogurt","salty","gluten-free"]}'],
    ["item-black-tea", rest1Id, "cat-drinks",
      "Egyptian Black Tea", "شاي مصري أسود",
      "Strong Ceylon tea brewed the Egyptian way — dark, bold and richly aromatic. Served in a traditional glass with mint sprigs and sugar cubes. Hot or iced on request.",
      "شاي سيلاني قوي مُعَدَّ على الطريقة المصرية — داكن وجريء وعطري. يُقدَّم في كوب تقليدي مع غصون نعناع وقطع سكر. ساخن أو مثلج عند الطلب.",
      15.0, "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":10,"tags":["hot","tea","tradition","caffeine","vegan"]}'],
    ["item-om-ali", rest1Id, "cat-desserts",
      "Hot Om Ali Dessert", "أم علي بالفرن",
      "Egypt's beloved national dessert — crispy puff pastry soaked in warm sweetened milk, baked with pistachio, almond, coconut and raisins, crowned with whipped cream caramelized on top.",
      "الحلوى الوطنية المصرية المحبوبة — فطير مقرمش منقوع في حليب دافئ محلى، مخبوز مع الفستق واللوز وجوز الهند والزبيب، متوج بقشطة مخفوقة ومكرملة من الأعلى.",
      75.0, "https://images.unsplash.com/photo-1587314168485-3236d6710814?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":450,"tags":["sweet","nuts","milk","warm","traditional","vegetarian"]}'],
    ["item-kunafa", rest1Id, "cat-desserts",
      "Kunafa with Cream Cheese", "كنافة بالقشطة والجبن",
      "Golden crispy kataifi pastry filled with fresh cream cheese and ashta, baked until amber-golden then drenched in orange-blossom sugar syrup. Topped with crushed pistachios and rose petals.",
      "كنافة قطايف ذهبية مقرمشة محشوة بالجبن القريش الطازج والقشطة، مخبوزة حتى تصبح ذهبية كالعنبر ثم مُغمَّرة في قطر بماء الزهر. مُزيَّنة بفستق مطحون وبتلات ورد.",
      85.0, "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":520,"tags":["sweet","cheese","syrup","pistachio","traditional","vegetarian"]}'],
    ["item-basbousa", rest1Id, "cat-desserts",
      "Basbousa (Semolina Cake)", "بسبوسة بالسميد",
      "Classic moist Egyptian semolina cake soaked in vanilla-and-rose-water syrup, topped with a whole blanched almond. Baked in our clay oven for authentic texture.",
      "كيكة سميد مصرية كلاسيكية رطبة منقوعة في قطر بالفانيليا وماء الورد، متوجة بلوزة مقشرة كاملة. مخبوزة في فرننا الطيني للقوام الأصيل.",
      50.0, "https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":380,"tags":["sweet","semolina","syrup","rose-water","traditional","vegetarian"]}'],
    ["item-rice-pudding", rest1Id, "cat-desserts",
      "Roz Bel Laban (Rice Pudding)", "رز بلبن كريمي",
      "Egyptian short-grain rice simmered in full-fat milk with sugar, rose water and mastic, chilled and served cold with cinnamon and crushed pistachio.",
      "أرز مصري قصير الحبة مطبوخ في حليب كامل الدسم مع السكر وماء الورد والمستكة، مُبرَّد ويُقدَّم بارداً مع رشة قرفة وفستق مطحون.",
      45.0, "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":290,"tags":["sweet","milk","cold","cinnamon","gluten-free","vegetarian"]}'],
    ["item-turkish-coffee", rest2Id, "cat-pyra-coffee",
      "Egyptian Double Turkish Coffee", "قهوة تركي مضاعفة",
      "Dark-roasted Arabica beans finely ground and slow-brewed in a traditional copper cezve with whole green cardamom pods until a thick, velvety crema forms. Served in an ornate demitasse.",
      "حبوب أرابيكا محمصة داكنة مطحونة ناعماً ومُعدَّة ببطء في جزوة نحاسية تقليدية مع حبوب هيل أخضر كاملة حتى تتكون كريمة مخملية. تُقدَّم في فنجان ديمي تاس منقوش.",
      40.0, "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":10,"tags":["hot","coffee","strong","cardamom","traditional","vegan"]}'],
    ["item-cappuccino", rest2Id, "cat-pyra-coffee",
      "Creamy Cappuccino", "كابتشينو كريمي",
      "Classic Italian-style cappuccino: double espresso shot, silky micro-foamed whole milk and a generous dome of velvet milk foam. Dusted with finest Belgian cocoa powder.",
      "كابتشينو كلاسيكي: جرعة مزدوجة من الإسبريسو الطازج وحليب كامل الدسم مُرغِّد وقبة سخية من رغوة الحليب المخملية. مُغبَّرة بمسحوق كاكاو بلجيكي فاخر.",
      65.0, "https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":120,"tags":["hot","coffee","milk","foam","espresso"]}'],
    ["item-espresso", rest2Id, "cat-pyra-coffee",
      "Double Espresso Shot", "دبل إسبريسو",
      "Two ristretto shots of our single-origin Ethiopian Yirgacheffe beans, pulled at 9 bars of pressure for a complex, fruity and darkly sweet cup.",
      "جرعتا ريستريتو من حبوب إثيوبية يرجاتشيفي مُسحوبة بضغط 9 بار لكوب معقد وفاكهي وحلو داكن.",
      50.0, "https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":5,"tags":["hot","coffee","strong","bold","vegan"]}'],
    ["item-mint-tea", rest2Id, "cat-pyra-coffee",
      "Moroccan Fresh Mint Tea", "شاي نعناع مغربي طازج",
      "Premium Moroccan gunpowder green tea steeped with fresh spearmint leaves and sweetened with amber cane sugar. Poured high for maximum aroma.",
      "شاي البارود الأخضر المغربي الممتاز منقوع مع أوراق النعناع الطازجة ومُحلَّى بسكر القصب الأصفر الأصيل. يُصب من علو لأقصى عطر.",
      30.0, "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":40,"tags":["hot","tea","mint","herbal","vegan","digestive"]}'],
    ["item-nescafe", rest2Id, "cat-pyra-coffee",
      "Nescafe Gold with Cream", "نسكافيه جولد مع كريمة",
      "Rich mug of Nescafe Gold dissolved in hot water, finished with warmed full-cream milk and a swirl of whipped cream. Simple, comforting and perfect any time of day.",
      "كوب غني من قهوة نسكافيه جولد مذابة في ماء ساخن، مُنهاة بحليب كامل الدسم دافئ ودوامة كريمة مخفوقة. بسيطة ومريحة ومثالية لأي وقت.",
      40.0, "https://images.unsplash.com/photo-1507941097613-9f2157b69235?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":80,"tags":["hot","coffee","instant","milk","creamy"]}'],
    ["item-green-tea", rest2Id, "cat-pyra-coffee",
      "Green Tea with Fresh Ginger", "شاي أخضر مع زنجبيل طازج",
      "Premium Japanese Sencha green tea steeped at 75 degrees, served with fresh peeled ginger slices and a honeycomb wedge. Calming and immune-boosting.",
      "شاي سنشا ياباني ممتاز منقوع عند 75 درجة مئوية، يُقدَّم مع شرائح طازجة من جذر الزنجبيل المقشر وقرص عسل. مهدئ ومعزز للمناعة.",
      35.0, "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":20,"tags":["hot","tea","antioxidant","ginger","immune","vegan"]}'],
    ["item-ful-taameya", rest2Id, "cat-pyra-breakfast",
      "Ful & Taameya Breakfast Basket", "سلة إفطار فول وطعمية",
      "The quintessential Egyptian breakfast — creamy slow-cooked fava beans with cumin and olive oil, alongside 4 crispy green falafel, served with baladi bread, tomato, rocket and pickles.",
      "الإفطار المصري بامتياز — فول مدمس كريمي بطيء الطهي بالكمون وزيت الزيتون، إلى جانب 4 قطع طعمية خضراء مقرمشة، تُقدَّم مع خبز بلدي وطماطم وجرجير ومخللات.",
      90.0, "https://images.unsplash.com/photo-1590412200988-a436970781fa?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":480,"tags":["vegetarian","vegan","traditional","fava-beans","falafel","high-protein"]}'],
    ["item-feteer", rest2Id, "cat-pyra-breakfast",
      "Feteer Meshaltet (Layered Pastry)", "فطير مشلتت",
      "Egypt's legendary multi-layered pastry — hand-stretched paper-thin dough folded with clarified butter until impossibly flaky. Served from the clay oven with clotted cream, honey and black seed jam.",
      "المعجنات الطبقية الأسطورية المصرية — عجينة رقيقة كالورق ممدودة يدوياً ومطوية مع السمن البلدي حتى تصبح هشة وخفيفة. تُقدَّم من الفرن الطيني مع قشطة وعسل ومربى حبة البركة.",
      110.0, "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":650,"tags":["vegetarian","buttery","flaky","traditional","wheat","honey"]}'],
    ["item-shakshuka", rest2Id, "cat-pyra-breakfast",
      "Classic Egyptian Shakshuka", "شكشوكة مصرية كلاسيكية",
      "Three farm-fresh eggs poached in a cast-iron skillet of slow-cooked tomatoes, sweet peppers, garlic and Egyptian spices, garnished with crumbled feta, parsley and chili flakes.",
      "ثلاث بيضات طازجة مسلوقة في مقلاة حديدية من طماطم مطبوخة ببطء وفلفل حلو وثوم وبهارات مصرية، مُزيَّنة بجبن فيتا مفتت وبقدونس ورقائق شيلي.",
      95.0, "https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":380,"tags":["vegetarian","eggs","tomato","spicy","iron","protein"]}'],
    ["item-liver", rest2Id, "cat-pyra-breakfast",
      "Alexandrian Spiced Liver Sandwich", "ساندوتش كبدة إسكندرانية",
      "Thinly sliced beef liver flash-fried with chili, cumin, garlic and green pepper in the Alexandrian style, served in a baladi roll with tahina and sliced tomato.",
      "شرائح رفيعة من كبدة البتلو مقلية سريعاً مع الشيلي والكمون والثوم والفلفل الأخضر على الطريقة الإسكندرانية، تُقدَّم في خبزة بلدي طازجة مع طحينة وطماطم مشرحة.",
      70.0, "https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":420,"tags":["halal","spicy","liver","alexandrian","street-food","iron"]}'],
    ["item-cheese-plate", rest2Id, "cat-pyra-breakfast",
      "Egyptian Baladi Cheese Platter", "طبق جبن بلدي مصري",
      "Rustic board of sliced white Egyptian Baladi cheese, creamy labneh with za'atar, brined olives, cucumber, ripe tomatoes and green onion. Served with warm baladi bread.",
      "لوح ريفي من جبن بلدي مصري أبيض مشرح وجبنة لبنة بالزعتر وزيتون محلول وخيار وطماطم ناضجة وبصل أخضر. يُقدَّم مع خبز بلدي دافئ.",
      80.0, "https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":350,"tags":["vegetarian","cheese","olives","tomato","calcium"]}'],
    ["item-orange-juice", rest2Id, "cat-pyra-juices",
      "Fresh Squeezed Orange Juice", "عصير برتقال معصور طازج",
      "Seven freshly hand-squeezed Egyptian Balady oranges — no sugar, no water, no concentrates. Pure liquid sunshine bursting with Vitamin C.",
      "سبع برتقالات بلدي مصرية معصورة يدوياً طازجة — بدون سكر مضاف ولا ماء ولا مركزات. شمس سائلة نقية مفعمة بفيتامين ج.",
      55.0, "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":110,"tags":["cold","fresh","vitamin-c","no-sugar","vegan","citrus"]}'],
    ["item-guava-juice", rest2Id, "cat-pyra-juices",
      "Egyptian Guava Nectar", "عصير جوافة مصرية",
      "Thick, fragrant Egyptian guavas blended until creamy with cold milk and honey, strained to a velvet-smooth nectar.",
      "جوافة مصرية سميكة وعطرية ممزوجة حتى تصبح كريمية مع الحليب البارد والعسل، مصفاة إلى رحيق ناعم كالمخمل.",
      60.0, "https://images.unsplash.com/photo-1553562912-7b6d2c5a96e0?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":150,"tags":["cold","fresh","tropical","vitamin-c","guava"]}'],
    ["item-watermelon", rest2Id, "cat-pyra-juices",
      "Iced Watermelon Juice", "عصير بطيخ مثلج",
      "Seedless watermelon blended fresh with lime and mint, served over crushed ice in a salt-rimmed glass. Outrageously hydrating on a scorching Giza afternoon.",
      "بطيخ بدون بذور ممزوج طازجاً مع الليم والنعناع، يُقدَّم على ثلج مجروش في كوب حافته ملح. مرطب بشكل مذهل في ظهيرة جيزاوية محرقة.",
      50.0, "https://images.unsplash.com/photo-1563248369-a5e5d76e81af?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":90,"tags":["cold","fresh","hydrating","vegan","no-sugar"]}'],
    ["item-mango-smoothie", rest2Id, "cat-pyra-juices",
      "Mango & Banana Power Smoothie", "سموذي مانجو وموز",
      "Thick tropical smoothie blending Alphonso mango, ripe banana, Greek yogurt and honey. Packed with natural energy, potassium and vitamins.",
      "سموذي كثيف استوائي يجمع مانجو الفونسو وموز ناضج وزبادي يوناني وعسل. مليء بالطاقة الطبيعية والبوتاسيوم والفيتامينات.",
      75.0, "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":230,"tags":["cold","thick","tropical","energy","protein","vegetarian"]}'],
    ["item-konafa-pyra", rest2Id, "cat-pyra-pastries",
      "Konafa bil Ashta (Cream Kunafa)", "كنافة بالقشطة والكريمة",
      "Signature kunafa — golden shredded kataifi pastry hugging house-made ashta and rose-scented mozzarella, baked in a copper tray, served still sizzling, soaked in sugar-rose syrup.",
      "كنافة مميزة — قطايف مبشورة ذهبية تحتضن القشطة الطازجة منزلية الصنع والموزاريلا المعطرة بالورد، مخبوزة في صينية نحاسية وتُقدَّم وهي لا تزال تطقطق منقوعة في قطر الورد.",
      80.0, "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":490,"tags":["sweet","cream","syrup","pistachio","traditional","vegetarian"]}'],
    ["item-croissant", rest2Id, "cat-pyra-pastries",
      "Butter Croissant (Freshly Baked)", "كرواسان زبدة طازج",
      "Classically laminated all-butter croissant baked in-house every morning until gloriously golden and shatteringly flaky. Served warm with apricot jam and powdered sugar.",
      "كرواسان زبدة كلاسيكي مُرقَّق مخبوز في المقهى كل صباح حتى يصبح ذهبياً وهشاً بشكل رائع. يُقدَّم دافئاً مع مربى المشمش ورشة سكر ناعم.",
      45.0, "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":340,"tags":["pastry","buttery","flaky","breakfast","wheat","vegetarian"]}'],
    ["item-cake-slice", rest2Id, "cat-pyra-pastries",
      "Chef's Daily Cake Slice", "شريحة كيكة الشيف اليومية",
      "Our pastry chef bakes a different cake every morning — carrot & walnut, dark Belgian chocolate ganache or strawberry chantilly. Ask your server for today's flavour.",
      "يخبز معلم المعجنات كيكة مختلفة كل صباح — الجزر والجوز أو غاناش الشوكولاتة البلجيكية أو شانتيي الفراولة. اسأل خادمك عن نكهة اليوم.",
      60.0, "https://images.unsplash.com/photo-1519915028121-7d3463d20b13?w=800&auto=format&fit=crop&q=90", 1,
      '{"calories":380,"tags":["sweet","cake","fresh","daily","seasonal","vegetarian"]}'],
  ];

  for (const [id, biz, cat, name, name_ar, desc, desc_ar, price, img, avail, tjson] of items) {
    await sql`
      INSERT INTO menu_items (id, business_id, category_id, name, name_ar, description, description_ar, price, image_url, is_available, translations_json)
      VALUES (${id}, ${biz}, ${cat}, ${name}, ${name_ar}, ${desc}, ${desc_ar}, ${price}, ${img}, ${avail}, ${tjson})
      ON CONFLICT (id) DO UPDATE SET
        name              = EXCLUDED.name,
        name_ar           = EXCLUDED.name_ar,
        description       = EXCLUDED.description,
        description_ar    = EXCLUDED.description_ar,
        price             = EXCLUDED.price,
        image_url         = EXCLUDED.image_url,
        is_available      = EXCLUDED.is_available,
        translations_json = EXCLUDED.translations_json
    `;
  }
  console.log("✅ " + items.length + " menu items upserted");

  await sql`
    INSERT INTO promotions (id, business_id, type, title, title_ar, description, description_ar, item_id, discount_price, status)
    VALUES (
      'promo-kebab-mix', ${rest1Id}, 'SPECIAL_OFFER',
      'Mix Grill Family Special', 'عرض المشويات العائلي',
      'Get 20% off the legendary Mix Grill Platter — perfect for the whole table. Tonight only!',
      'خصم 20% على طبق المشويات المشكلة الأسطوري — مثالي لكامل الطاولة. الليلة فقط!',
      'item-kebab-mix', 360.0, 'ACTIVE'
    )
    ON CONFLICT (id) DO UPDATE SET
      description    = EXCLUDED.description,
      description_ar = EXCLUDED.description_ar,
      discount_price = EXCLUDED.discount_price,
      status         = EXCLUDED.status
  `;

  await sql`
    INSERT INTO promotions (id, business_id, type, title, title_ar, description, description_ar, item_id, discount_price, status)
    VALUES (
      'promo-konafa-pyra', ${rest2Id}, 'SPECIAL_OFFER',
      'Sunset Kunafa Deal', 'عرض كنافة الغروب',
      'Order Konafa bil Ashta between 5 PM and 7 PM and get it at a special sunset price!',
      'اطلب كنافة بالقشطة بين الساعة 5 و7 مساءً واحصل عليها بسعر خاص لوقت الغروب!',
      'item-konafa-pyra', 60.0, 'ACTIVE'
    )
    ON CONFLICT (id) DO NOTHING
  `;

  console.log("✅ Promotions upserted");
  console.log("🎉 Done!");
  await sql.end();
}

seed().catch((err) => {
  console.error("❌ Seed failed:", err.message);
  process.exit(1);
});
